import { useState } from 'react';
import { ChevronDown } from 'lucide-react';

interface FAQItem {
  question: string;
  answer: string;
}

const faqs: FAQItem[] = [
  {
    question: 'Is this QR code generator really free?',
    answer: 'Yes, QR Nexus is completely free to use. Generate unlimited QR codes with no hidden fees, no signup required, and no watermarks on your downloads.',
  },
  {
    question: 'Are my QR codes private and secure?',
    answer: 'Absolutely. All QR codes are generated client-side in your browser using JavaScript. Your data never leaves your device or gets sent to any server, ensuring complete privacy and security.',
  },
  {
    question: 'What types of QR codes can I create?',
    answer: 'QR Nexus supports 7 QR code types: URL/website links, plain text, WiFi network access, vCard contact cards, email messages, phone calls, and SMS text messages.',
  },
  {
    question: 'Can I add my logo to a QR code?',
    answer: 'Yes! You can upload your logo image (PNG, JPG, SVG) and it will be placed in the center of your QR code. We recommend using Medium or High error correction for best scanning results with logos.',
  },
  {
    question: 'What file formats can I download?',
    answer: 'You can download your QR code in three formats: PNG (high-resolution raster image), SVG (scalable vector for print), and PDF (print-ready document).',
  },
  {
    question: 'Do the QR codes expire?',
    answer: 'No, the QR codes you generate are static and never expire. They will work forever as long as the content they link to remains valid.',
  },
  {
    question: 'Will my QR code work with any scanner?',
    answer: 'Yes, all QR codes generated by QR Nexus are standard-compliant and work with any QR code scanner app, smartphone camera (iOS and Android), and barcode scanning devices.',
  },
  {
    question: 'Can I use QR codes for commercial purposes?',
    answer: 'Yes, all QR codes generated are free for both personal and commercial use. Use them on business cards, product packaging, marketing materials, advertisements, and more.',
  },
  {
    question: 'What is error correction and why does it matter?',
    answer: 'Error correction allows QR codes to be scanned even if partially damaged or covered. Low (L) = 7% recovery, Medium (M) = 15%, Quartile (Q) = 25%, High (H) = 30%. Use Medium or higher when adding a logo.',
  },
  {
    question: 'How do I create a WiFi QR code?',
    answer: "Select 'WiFi' as the QR code type, enter your network name (SSID), password, and security type (WPA/WPA2, WEP, or None). When someone scans the code, their device will automatically connect to your network.",
  },
];

function FAQAccordion({ item }: { item: FAQItem }) {
  const [open, setOpen] = useState(false);

  return (
    <div className="bg-white/5 border border-white/10 rounded-xl overflow-hidden mb-3">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between p-4 sm:p-5 text-left"
        aria-expanded={open}
      >
        <span className="text-sm sm:text-base font-semibold text-[#f0f0f0] pr-4">
          {item.question}
        </span>
        <ChevronDown
          className={`w-5 h-5 text-[#f0f0f0]/40 flex-shrink-0 transition-transform duration-300 ${
            open ? 'rotate-180' : ''
          }`}
        />
      </button>
      <div
        className={`overflow-hidden transition-all duration-300 ${
          open ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'
        }`}
      >
        <div className="px-4 sm:px-5 pb-4 sm:pb-5">
          <p className="text-sm text-[#f0f0f0]/60 leading-relaxed">
            {item.answer}
          </p>
        </div>
      </div>
    </div>
  );
}

export default function FAQ() {
  return (
    <section id="faq" className="py-20 scroll-mt-20">
      <div className="max-w-[800px] mx-auto px-4 sm:px-6">
        <div className="text-center mb-12">
          <h2 className="text-2xl sm:text-3xl lg:text-4xl font-bold text-[#f0f0f0]">
            Frequently Asked Questions
          </h2>
          <p className="mt-3 text-sm sm:text-base text-[#f0f0f0]/50">
            Everything you need to know about QR codes and our generator.
          </p>
        </div>

        <div>
          {faqs.map((faq, i) => (
            <FAQAccordion key={i} item={faq} />
          ))}
        </div>
      </div>
    </section>
  );
}
